//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace TAUP2C.Dobberman.Phone.DobbermanService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Report", Namespace="http://schemas.datacontract.org/2004/07/TAUP2C.Dobberman.WebRole.Services")]
    public partial class Report : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TAUP2C.Dobberman.Phone.DobbermanService.Authority AuthorityField;
        
        private int AuthorityIdField;
        
        private System.DateTime DateField;
        
        private string DescriptionField;
        
        private string LocationField;
        
        private string MoodField;
        
        private string PhotoField;
        
        private int ReportIdField;
        
        private TAUP2C.Dobberman.Phone.DobbermanService.User UserField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TAUP2C.Dobberman.Phone.DobbermanService.Authority Authority {
            get {
                return this.AuthorityField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorityField, value) != true)) {
                    this.AuthorityField = value;
                    this.RaisePropertyChanged("Authority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuthorityId {
            get {
                return this.AuthorityIdField;
            }
            set {
                if ((this.AuthorityIdField.Equals(value) != true)) {
                    this.AuthorityIdField = value;
                    this.RaisePropertyChanged("AuthorityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mood {
            get {
                return this.MoodField;
            }
            set {
                if ((object.ReferenceEquals(this.MoodField, value) != true)) {
                    this.MoodField = value;
                    this.RaisePropertyChanged("Mood");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReportId {
            get {
                return this.ReportIdField;
            }
            set {
                if ((this.ReportIdField.Equals(value) != true)) {
                    this.ReportIdField = value;
                    this.RaisePropertyChanged("ReportId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TAUP2C.Dobberman.Phone.DobbermanService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authority", Namespace="http://schemas.datacontract.org/2004/07/TAUP2C.Dobberman.WebRole.Services")]
    public partial class Authority : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int AuthorityIdField;
        
        private TAUP2C.Dobberman.Phone.DobbermanService.Category CategoryField;
        
        private int CategoryIdField;
        
        private string FacebookPageField;
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> ReportsField;
        
        private double ScoreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuthorityId {
            get {
                return this.AuthorityIdField;
            }
            set {
                if ((this.AuthorityIdField.Equals(value) != true)) {
                    this.AuthorityIdField = value;
                    this.RaisePropertyChanged("AuthorityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TAUP2C.Dobberman.Phone.DobbermanService.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookPage {
            get {
                return this.FacebookPageField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookPageField, value) != true)) {
                    this.FacebookPageField = value;
                    this.RaisePropertyChanged("FacebookPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> Reports {
            get {
                return this.ReportsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportsField, value) != true)) {
                    this.ReportsField = value;
                    this.RaisePropertyChanged("Reports");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/TAUP2C.Dobberman.WebRole.Services")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EmailField;
        
        private string NameField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/TAUP2C.Dobberman.WebRole.Services")]
    public partial class Category : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> AuthoritiesField;
        
        private int CategoryIdField;
        
        private string DescriptionField;
        
        private string NameField;
        
        private string PictureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> Authorities {
            get {
                return this.AuthoritiesField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthoritiesField, value) != true)) {
                    this.AuthoritiesField = value;
                    this.RaisePropertyChanged("Authorities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DobbermanService.IDobbermanService")]
    public interface IDobbermanService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/GetReportsByUserId", ReplyAction="http://tempuri.org/IDobbermanService/GetReportsByUserIdResponse")]
        System.IAsyncResult BeginGetReportsByUserId(int userId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> EndGetReportsByUserId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/GetReportsByAuthorityId", ReplyAction="http://tempuri.org/IDobbermanService/GetReportsByAuthorityIdResponse")]
        System.IAsyncResult BeginGetReportsByAuthorityId(int authorityId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> EndGetReportsByAuthorityId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/GetAllReportsWithLocation", ReplyAction="http://tempuri.org/IDobbermanService/GetAllReportsWithLocationResponse")]
        System.IAsyncResult BeginGetAllReportsWithLocation(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> EndGetAllReportsWithLocation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/GetAllAuthorities", ReplyAction="http://tempuri.org/IDobbermanService/GetAllAuthoritiesResponse")]
        System.IAsyncResult BeginGetAllAuthorities(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> EndGetAllAuthorities(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/GetSortedAuthorities", ReplyAction="http://tempuri.org/IDobbermanService/GetSortedAuthoritiesResponse")]
        System.IAsyncResult BeginGetSortedAuthorities(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> EndGetSortedAuthorities(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/GetAuthoritiesByCategoryId", ReplyAction="http://tempuri.org/IDobbermanService/GetAuthoritiesByCategoryIdResponse")]
        System.IAsyncResult BeginGetAuthoritiesByCategoryId(int categoryId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> EndGetAuthoritiesByCategoryId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/GetAllCategories", ReplyAction="http://tempuri.org/IDobbermanService/GetAllCategoriesResponse")]
        System.IAsyncResult BeginGetAllCategories(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Category> EndGetAllCategories(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/CreateNewReport", ReplyAction="http://tempuri.org/IDobbermanService/CreateNewReportResponse")]
        System.IAsyncResult BeginCreateNewReport(TAUP2C.Dobberman.Phone.DobbermanService.Report report, System.AsyncCallback callback, object asyncState);
        
        int EndCreateNewReport(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/CreateNewUser", ReplyAction="http://tempuri.org/IDobbermanService/CreateNewUserResponse")]
        System.IAsyncResult BeginCreateNewUser(TAUP2C.Dobberman.Phone.DobbermanService.User user, System.AsyncCallback callback, object asyncState);
        
        int EndCreateNewUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/CreateNewAuthority", ReplyAction="http://tempuri.org/IDobbermanService/CreateNewAuthorityResponse")]
        System.IAsyncResult BeginCreateNewAuthority(TAUP2C.Dobberman.Phone.DobbermanService.Authority authority, System.AsyncCallback callback, object asyncState);
        
        int EndCreateNewAuthority(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/CreateNewCategory", ReplyAction="http://tempuri.org/IDobbermanService/CreateNewCategoryResponse")]
        System.IAsyncResult BeginCreateNewCategory(TAUP2C.Dobberman.Phone.DobbermanService.Category category, System.AsyncCallback callback, object asyncState);
        
        int EndCreateNewCategory(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDobbermanServiceChannel : TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetReportsByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetReportsByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetReportsByAuthorityIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetReportsByAuthorityIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllReportsWithLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllReportsWithLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllAuthoritiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllAuthoritiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSortedAuthoritiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSortedAuthoritiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAuthoritiesByCategoryIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAuthoritiesByCategoryIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Category> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Category>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateNewReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateNewReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateNewUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateNewUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateNewAuthorityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateNewAuthorityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateNewCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateNewCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DobbermanServiceClient : System.ServiceModel.ClientBase<TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService>, TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService {
        
        private BeginOperationDelegate onBeginGetReportsByUserIdDelegate;
        
        private EndOperationDelegate onEndGetReportsByUserIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetReportsByUserIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetReportsByAuthorityIdDelegate;
        
        private EndOperationDelegate onEndGetReportsByAuthorityIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetReportsByAuthorityIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllReportsWithLocationDelegate;
        
        private EndOperationDelegate onEndGetAllReportsWithLocationDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllReportsWithLocationCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllAuthoritiesDelegate;
        
        private EndOperationDelegate onEndGetAllAuthoritiesDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllAuthoritiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSortedAuthoritiesDelegate;
        
        private EndOperationDelegate onEndGetSortedAuthoritiesDelegate;
        
        private System.Threading.SendOrPostCallback onGetSortedAuthoritiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAuthoritiesByCategoryIdDelegate;
        
        private EndOperationDelegate onEndGetAuthoritiesByCategoryIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetAuthoritiesByCategoryIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllCategoriesDelegate;
        
        private EndOperationDelegate onEndGetAllCategoriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllCategoriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateNewReportDelegate;
        
        private EndOperationDelegate onEndCreateNewReportDelegate;
        
        private System.Threading.SendOrPostCallback onCreateNewReportCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateNewUserDelegate;
        
        private EndOperationDelegate onEndCreateNewUserDelegate;
        
        private System.Threading.SendOrPostCallback onCreateNewUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateNewAuthorityDelegate;
        
        private EndOperationDelegate onEndCreateNewAuthorityDelegate;
        
        private System.Threading.SendOrPostCallback onCreateNewAuthorityCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateNewCategoryDelegate;
        
        private EndOperationDelegate onEndCreateNewCategoryDelegate;
        
        private System.Threading.SendOrPostCallback onCreateNewCategoryCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DobbermanServiceClient() {
        }
        
        public DobbermanServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DobbermanServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DobbermanServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DobbermanServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetReportsByUserIdCompletedEventArgs> GetReportsByUserIdCompleted;
        
        public event System.EventHandler<GetReportsByAuthorityIdCompletedEventArgs> GetReportsByAuthorityIdCompleted;
        
        public event System.EventHandler<GetAllReportsWithLocationCompletedEventArgs> GetAllReportsWithLocationCompleted;
        
        public event System.EventHandler<GetAllAuthoritiesCompletedEventArgs> GetAllAuthoritiesCompleted;
        
        public event System.EventHandler<GetSortedAuthoritiesCompletedEventArgs> GetSortedAuthoritiesCompleted;
        
        public event System.EventHandler<GetAuthoritiesByCategoryIdCompletedEventArgs> GetAuthoritiesByCategoryIdCompleted;
        
        public event System.EventHandler<GetAllCategoriesCompletedEventArgs> GetAllCategoriesCompleted;
        
        public event System.EventHandler<CreateNewReportCompletedEventArgs> CreateNewReportCompleted;
        
        public event System.EventHandler<CreateNewUserCompletedEventArgs> CreateNewUserCompleted;
        
        public event System.EventHandler<CreateNewAuthorityCompletedEventArgs> CreateNewAuthorityCompleted;
        
        public event System.EventHandler<CreateNewCategoryCompletedEventArgs> CreateNewCategoryCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginGetReportsByUserId(int userId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetReportsByUserId(userId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndGetReportsByUserId(System.IAsyncResult result) {
            return base.Channel.EndGetReportsByUserId(result);
        }
        
        private System.IAsyncResult OnBeginGetReportsByUserId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginGetReportsByUserId(userId, callback, asyncState);
        }
        
        private object[] OnEndGetReportsByUserId(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndGetReportsByUserId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetReportsByUserIdCompleted(object state) {
            if ((this.GetReportsByUserIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetReportsByUserIdCompleted(this, new GetReportsByUserIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetReportsByUserIdAsync(int userId) {
            this.GetReportsByUserIdAsync(userId, null);
        }
        
        public void GetReportsByUserIdAsync(int userId, object userState) {
            if ((this.onBeginGetReportsByUserIdDelegate == null)) {
                this.onBeginGetReportsByUserIdDelegate = new BeginOperationDelegate(this.OnBeginGetReportsByUserId);
            }
            if ((this.onEndGetReportsByUserIdDelegate == null)) {
                this.onEndGetReportsByUserIdDelegate = new EndOperationDelegate(this.OnEndGetReportsByUserId);
            }
            if ((this.onGetReportsByUserIdCompletedDelegate == null)) {
                this.onGetReportsByUserIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetReportsByUserIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetReportsByUserIdDelegate, new object[] {
                        userId}, this.onEndGetReportsByUserIdDelegate, this.onGetReportsByUserIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginGetReportsByAuthorityId(int authorityId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetReportsByAuthorityId(authorityId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndGetReportsByAuthorityId(System.IAsyncResult result) {
            return base.Channel.EndGetReportsByAuthorityId(result);
        }
        
        private System.IAsyncResult OnBeginGetReportsByAuthorityId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int authorityId = ((int)(inValues[0]));
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginGetReportsByAuthorityId(authorityId, callback, asyncState);
        }
        
        private object[] OnEndGetReportsByAuthorityId(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndGetReportsByAuthorityId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetReportsByAuthorityIdCompleted(object state) {
            if ((this.GetReportsByAuthorityIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetReportsByAuthorityIdCompleted(this, new GetReportsByAuthorityIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetReportsByAuthorityIdAsync(int authorityId) {
            this.GetReportsByAuthorityIdAsync(authorityId, null);
        }
        
        public void GetReportsByAuthorityIdAsync(int authorityId, object userState) {
            if ((this.onBeginGetReportsByAuthorityIdDelegate == null)) {
                this.onBeginGetReportsByAuthorityIdDelegate = new BeginOperationDelegate(this.OnBeginGetReportsByAuthorityId);
            }
            if ((this.onEndGetReportsByAuthorityIdDelegate == null)) {
                this.onEndGetReportsByAuthorityIdDelegate = new EndOperationDelegate(this.OnEndGetReportsByAuthorityId);
            }
            if ((this.onGetReportsByAuthorityIdCompletedDelegate == null)) {
                this.onGetReportsByAuthorityIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetReportsByAuthorityIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetReportsByAuthorityIdDelegate, new object[] {
                        authorityId}, this.onEndGetReportsByAuthorityIdDelegate, this.onGetReportsByAuthorityIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginGetAllReportsWithLocation(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllReportsWithLocation(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndGetAllReportsWithLocation(System.IAsyncResult result) {
            return base.Channel.EndGetAllReportsWithLocation(result);
        }
        
        private System.IAsyncResult OnBeginGetAllReportsWithLocation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginGetAllReportsWithLocation(callback, asyncState);
        }
        
        private object[] OnEndGetAllReportsWithLocation(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndGetAllReportsWithLocation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllReportsWithLocationCompleted(object state) {
            if ((this.GetAllReportsWithLocationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllReportsWithLocationCompleted(this, new GetAllReportsWithLocationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllReportsWithLocationAsync() {
            this.GetAllReportsWithLocationAsync(null);
        }
        
        public void GetAllReportsWithLocationAsync(object userState) {
            if ((this.onBeginGetAllReportsWithLocationDelegate == null)) {
                this.onBeginGetAllReportsWithLocationDelegate = new BeginOperationDelegate(this.OnBeginGetAllReportsWithLocation);
            }
            if ((this.onEndGetAllReportsWithLocationDelegate == null)) {
                this.onEndGetAllReportsWithLocationDelegate = new EndOperationDelegate(this.OnEndGetAllReportsWithLocation);
            }
            if ((this.onGetAllReportsWithLocationCompletedDelegate == null)) {
                this.onGetAllReportsWithLocationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllReportsWithLocationCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllReportsWithLocationDelegate, null, this.onEndGetAllReportsWithLocationDelegate, this.onGetAllReportsWithLocationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginGetAllAuthorities(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllAuthorities(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndGetAllAuthorities(System.IAsyncResult result) {
            return base.Channel.EndGetAllAuthorities(result);
        }
        
        private System.IAsyncResult OnBeginGetAllAuthorities(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginGetAllAuthorities(callback, asyncState);
        }
        
        private object[] OnEndGetAllAuthorities(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndGetAllAuthorities(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllAuthoritiesCompleted(object state) {
            if ((this.GetAllAuthoritiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllAuthoritiesCompleted(this, new GetAllAuthoritiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllAuthoritiesAsync() {
            this.GetAllAuthoritiesAsync(null);
        }
        
        public void GetAllAuthoritiesAsync(object userState) {
            if ((this.onBeginGetAllAuthoritiesDelegate == null)) {
                this.onBeginGetAllAuthoritiesDelegate = new BeginOperationDelegate(this.OnBeginGetAllAuthorities);
            }
            if ((this.onEndGetAllAuthoritiesDelegate == null)) {
                this.onEndGetAllAuthoritiesDelegate = new EndOperationDelegate(this.OnEndGetAllAuthorities);
            }
            if ((this.onGetAllAuthoritiesCompletedDelegate == null)) {
                this.onGetAllAuthoritiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllAuthoritiesCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllAuthoritiesDelegate, null, this.onEndGetAllAuthoritiesDelegate, this.onGetAllAuthoritiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginGetSortedAuthorities(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSortedAuthorities(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndGetSortedAuthorities(System.IAsyncResult result) {
            return base.Channel.EndGetSortedAuthorities(result);
        }
        
        private System.IAsyncResult OnBeginGetSortedAuthorities(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginGetSortedAuthorities(callback, asyncState);
        }
        
        private object[] OnEndGetSortedAuthorities(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndGetSortedAuthorities(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSortedAuthoritiesCompleted(object state) {
            if ((this.GetSortedAuthoritiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSortedAuthoritiesCompleted(this, new GetSortedAuthoritiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSortedAuthoritiesAsync() {
            this.GetSortedAuthoritiesAsync(null);
        }
        
        public void GetSortedAuthoritiesAsync(object userState) {
            if ((this.onBeginGetSortedAuthoritiesDelegate == null)) {
                this.onBeginGetSortedAuthoritiesDelegate = new BeginOperationDelegate(this.OnBeginGetSortedAuthorities);
            }
            if ((this.onEndGetSortedAuthoritiesDelegate == null)) {
                this.onEndGetSortedAuthoritiesDelegate = new EndOperationDelegate(this.OnEndGetSortedAuthorities);
            }
            if ((this.onGetSortedAuthoritiesCompletedDelegate == null)) {
                this.onGetSortedAuthoritiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSortedAuthoritiesCompleted);
            }
            base.InvokeAsync(this.onBeginGetSortedAuthoritiesDelegate, null, this.onEndGetSortedAuthoritiesDelegate, this.onGetSortedAuthoritiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginGetAuthoritiesByCategoryId(int categoryId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAuthoritiesByCategoryId(categoryId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndGetAuthoritiesByCategoryId(System.IAsyncResult result) {
            return base.Channel.EndGetAuthoritiesByCategoryId(result);
        }
        
        private System.IAsyncResult OnBeginGetAuthoritiesByCategoryId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int categoryId = ((int)(inValues[0]));
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginGetAuthoritiesByCategoryId(categoryId, callback, asyncState);
        }
        
        private object[] OnEndGetAuthoritiesByCategoryId(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndGetAuthoritiesByCategoryId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAuthoritiesByCategoryIdCompleted(object state) {
            if ((this.GetAuthoritiesByCategoryIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAuthoritiesByCategoryIdCompleted(this, new GetAuthoritiesByCategoryIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAuthoritiesByCategoryIdAsync(int categoryId) {
            this.GetAuthoritiesByCategoryIdAsync(categoryId, null);
        }
        
        public void GetAuthoritiesByCategoryIdAsync(int categoryId, object userState) {
            if ((this.onBeginGetAuthoritiesByCategoryIdDelegate == null)) {
                this.onBeginGetAuthoritiesByCategoryIdDelegate = new BeginOperationDelegate(this.OnBeginGetAuthoritiesByCategoryId);
            }
            if ((this.onEndGetAuthoritiesByCategoryIdDelegate == null)) {
                this.onEndGetAuthoritiesByCategoryIdDelegate = new EndOperationDelegate(this.OnEndGetAuthoritiesByCategoryId);
            }
            if ((this.onGetAuthoritiesByCategoryIdCompletedDelegate == null)) {
                this.onGetAuthoritiesByCategoryIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAuthoritiesByCategoryIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetAuthoritiesByCategoryIdDelegate, new object[] {
                        categoryId}, this.onEndGetAuthoritiesByCategoryIdDelegate, this.onGetAuthoritiesByCategoryIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginGetAllCategories(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllCategories(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Category> TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndGetAllCategories(System.IAsyncResult result) {
            return base.Channel.EndGetAllCategories(result);
        }
        
        private System.IAsyncResult OnBeginGetAllCategories(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginGetAllCategories(callback, asyncState);
        }
        
        private object[] OnEndGetAllCategories(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Category> retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndGetAllCategories(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllCategoriesCompleted(object state) {
            if ((this.GetAllCategoriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllCategoriesCompleted(this, new GetAllCategoriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllCategoriesAsync() {
            this.GetAllCategoriesAsync(null);
        }
        
        public void GetAllCategoriesAsync(object userState) {
            if ((this.onBeginGetAllCategoriesDelegate == null)) {
                this.onBeginGetAllCategoriesDelegate = new BeginOperationDelegate(this.OnBeginGetAllCategories);
            }
            if ((this.onEndGetAllCategoriesDelegate == null)) {
                this.onEndGetAllCategoriesDelegate = new EndOperationDelegate(this.OnEndGetAllCategories);
            }
            if ((this.onGetAllCategoriesCompletedDelegate == null)) {
                this.onGetAllCategoriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllCategoriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllCategoriesDelegate, null, this.onEndGetAllCategoriesDelegate, this.onGetAllCategoriesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginCreateNewReport(TAUP2C.Dobberman.Phone.DobbermanService.Report report, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateNewReport(report, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndCreateNewReport(System.IAsyncResult result) {
            return base.Channel.EndCreateNewReport(result);
        }
        
        private System.IAsyncResult OnBeginCreateNewReport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TAUP2C.Dobberman.Phone.DobbermanService.Report report = ((TAUP2C.Dobberman.Phone.DobbermanService.Report)(inValues[0]));
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginCreateNewReport(report, callback, asyncState);
        }
        
        private object[] OnEndCreateNewReport(System.IAsyncResult result) {
            int retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndCreateNewReport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateNewReportCompleted(object state) {
            if ((this.CreateNewReportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateNewReportCompleted(this, new CreateNewReportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateNewReportAsync(TAUP2C.Dobberman.Phone.DobbermanService.Report report) {
            this.CreateNewReportAsync(report, null);
        }
        
        public void CreateNewReportAsync(TAUP2C.Dobberman.Phone.DobbermanService.Report report, object userState) {
            if ((this.onBeginCreateNewReportDelegate == null)) {
                this.onBeginCreateNewReportDelegate = new BeginOperationDelegate(this.OnBeginCreateNewReport);
            }
            if ((this.onEndCreateNewReportDelegate == null)) {
                this.onEndCreateNewReportDelegate = new EndOperationDelegate(this.OnEndCreateNewReport);
            }
            if ((this.onCreateNewReportCompletedDelegate == null)) {
                this.onCreateNewReportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateNewReportCompleted);
            }
            base.InvokeAsync(this.onBeginCreateNewReportDelegate, new object[] {
                        report}, this.onEndCreateNewReportDelegate, this.onCreateNewReportCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginCreateNewUser(TAUP2C.Dobberman.Phone.DobbermanService.User user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateNewUser(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndCreateNewUser(System.IAsyncResult result) {
            return base.Channel.EndCreateNewUser(result);
        }
        
        private System.IAsyncResult OnBeginCreateNewUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TAUP2C.Dobberman.Phone.DobbermanService.User user = ((TAUP2C.Dobberman.Phone.DobbermanService.User)(inValues[0]));
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginCreateNewUser(user, callback, asyncState);
        }
        
        private object[] OnEndCreateNewUser(System.IAsyncResult result) {
            int retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndCreateNewUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateNewUserCompleted(object state) {
            if ((this.CreateNewUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateNewUserCompleted(this, new CreateNewUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateNewUserAsync(TAUP2C.Dobberman.Phone.DobbermanService.User user) {
            this.CreateNewUserAsync(user, null);
        }
        
        public void CreateNewUserAsync(TAUP2C.Dobberman.Phone.DobbermanService.User user, object userState) {
            if ((this.onBeginCreateNewUserDelegate == null)) {
                this.onBeginCreateNewUserDelegate = new BeginOperationDelegate(this.OnBeginCreateNewUser);
            }
            if ((this.onEndCreateNewUserDelegate == null)) {
                this.onEndCreateNewUserDelegate = new EndOperationDelegate(this.OnEndCreateNewUser);
            }
            if ((this.onCreateNewUserCompletedDelegate == null)) {
                this.onCreateNewUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateNewUserCompleted);
            }
            base.InvokeAsync(this.onBeginCreateNewUserDelegate, new object[] {
                        user}, this.onEndCreateNewUserDelegate, this.onCreateNewUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginCreateNewAuthority(TAUP2C.Dobberman.Phone.DobbermanService.Authority authority, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateNewAuthority(authority, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndCreateNewAuthority(System.IAsyncResult result) {
            return base.Channel.EndCreateNewAuthority(result);
        }
        
        private System.IAsyncResult OnBeginCreateNewAuthority(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TAUP2C.Dobberman.Phone.DobbermanService.Authority authority = ((TAUP2C.Dobberman.Phone.DobbermanService.Authority)(inValues[0]));
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginCreateNewAuthority(authority, callback, asyncState);
        }
        
        private object[] OnEndCreateNewAuthority(System.IAsyncResult result) {
            int retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndCreateNewAuthority(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateNewAuthorityCompleted(object state) {
            if ((this.CreateNewAuthorityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateNewAuthorityCompleted(this, new CreateNewAuthorityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateNewAuthorityAsync(TAUP2C.Dobberman.Phone.DobbermanService.Authority authority) {
            this.CreateNewAuthorityAsync(authority, null);
        }
        
        public void CreateNewAuthorityAsync(TAUP2C.Dobberman.Phone.DobbermanService.Authority authority, object userState) {
            if ((this.onBeginCreateNewAuthorityDelegate == null)) {
                this.onBeginCreateNewAuthorityDelegate = new BeginOperationDelegate(this.OnBeginCreateNewAuthority);
            }
            if ((this.onEndCreateNewAuthorityDelegate == null)) {
                this.onEndCreateNewAuthorityDelegate = new EndOperationDelegate(this.OnEndCreateNewAuthority);
            }
            if ((this.onCreateNewAuthorityCompletedDelegate == null)) {
                this.onCreateNewAuthorityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateNewAuthorityCompleted);
            }
            base.InvokeAsync(this.onBeginCreateNewAuthorityDelegate, new object[] {
                        authority}, this.onEndCreateNewAuthorityDelegate, this.onCreateNewAuthorityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginCreateNewCategory(TAUP2C.Dobberman.Phone.DobbermanService.Category category, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateNewCategory(category, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndCreateNewCategory(System.IAsyncResult result) {
            return base.Channel.EndCreateNewCategory(result);
        }
        
        private System.IAsyncResult OnBeginCreateNewCategory(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TAUP2C.Dobberman.Phone.DobbermanService.Category category = ((TAUP2C.Dobberman.Phone.DobbermanService.Category)(inValues[0]));
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginCreateNewCategory(category, callback, asyncState);
        }
        
        private object[] OnEndCreateNewCategory(System.IAsyncResult result) {
            int retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndCreateNewCategory(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateNewCategoryCompleted(object state) {
            if ((this.CreateNewCategoryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateNewCategoryCompleted(this, new CreateNewCategoryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateNewCategoryAsync(TAUP2C.Dobberman.Phone.DobbermanService.Category category) {
            this.CreateNewCategoryAsync(category, null);
        }
        
        public void CreateNewCategoryAsync(TAUP2C.Dobberman.Phone.DobbermanService.Category category, object userState) {
            if ((this.onBeginCreateNewCategoryDelegate == null)) {
                this.onBeginCreateNewCategoryDelegate = new BeginOperationDelegate(this.OnBeginCreateNewCategory);
            }
            if ((this.onEndCreateNewCategoryDelegate == null)) {
                this.onEndCreateNewCategoryDelegate = new EndOperationDelegate(this.OnEndCreateNewCategory);
            }
            if ((this.onCreateNewCategoryCompletedDelegate == null)) {
                this.onCreateNewCategoryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateNewCategoryCompleted);
            }
            base.InvokeAsync(this.onBeginCreateNewCategoryDelegate, new object[] {
                        category}, this.onEndCreateNewCategoryDelegate, this.onCreateNewCategoryCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService CreateChannel() {
            return new DobbermanServiceClientChannel(this);
        }
        
        private class DobbermanServiceClientChannel : ChannelBase<TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService>, TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService {
            
            public DobbermanServiceClientChannel(System.ServiceModel.ClientBase<TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetReportsByUserId(int userId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userId;
                System.IAsyncResult _result = base.BeginInvoke("GetReportsByUserId", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> EndGetReportsByUserId(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> _result = ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report>)(base.EndInvoke("GetReportsByUserId", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetReportsByAuthorityId(int authorityId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = authorityId;
                System.IAsyncResult _result = base.BeginInvoke("GetReportsByAuthorityId", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> EndGetReportsByAuthorityId(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> _result = ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report>)(base.EndInvoke("GetReportsByAuthorityId", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllReportsWithLocation(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllReportsWithLocation", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> EndGetAllReportsWithLocation(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> _result = ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report>)(base.EndInvoke("GetAllReportsWithLocation", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllAuthorities(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllAuthorities", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> EndGetAllAuthorities(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> _result = ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority>)(base.EndInvoke("GetAllAuthorities", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSortedAuthorities(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetSortedAuthorities", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> EndGetSortedAuthorities(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> _result = ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority>)(base.EndInvoke("GetSortedAuthorities", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAuthoritiesByCategoryId(int categoryId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = categoryId;
                System.IAsyncResult _result = base.BeginInvoke("GetAuthoritiesByCategoryId", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> EndGetAuthoritiesByCategoryId(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority> _result = ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Authority>)(base.EndInvoke("GetAuthoritiesByCategoryId", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllCategories(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllCategories", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Category> EndGetAllCategories(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Category> _result = ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Category>)(base.EndInvoke("GetAllCategories", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateNewReport(TAUP2C.Dobberman.Phone.DobbermanService.Report report, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = report;
                System.IAsyncResult _result = base.BeginInvoke("CreateNewReport", _args, callback, asyncState);
                return _result;
            }
            
            public int EndCreateNewReport(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("CreateNewReport", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateNewUser(TAUP2C.Dobberman.Phone.DobbermanService.User user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("CreateNewUser", _args, callback, asyncState);
                return _result;
            }
            
            public int EndCreateNewUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("CreateNewUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateNewAuthority(TAUP2C.Dobberman.Phone.DobbermanService.Authority authority, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = authority;
                System.IAsyncResult _result = base.BeginInvoke("CreateNewAuthority", _args, callback, asyncState);
                return _result;
            }
            
            public int EndCreateNewAuthority(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("CreateNewAuthority", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateNewCategory(TAUP2C.Dobberman.Phone.DobbermanService.Category category, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = category;
                System.IAsyncResult _result = base.BeginInvoke("CreateNewCategory", _args, callback, asyncState);
                return _result;
            }
            
            public int EndCreateNewCategory(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("CreateNewCategory", _args, result)));
                return _result;
            }
        }
    }
}
