//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace TAUP2C.Dobberman.Phone.DobbermanService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Report", Namespace="http://schemas.datacontract.org/2004/07/TAUP2C.Dobberman.Web.Services")]
    public partial class Report : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TAUP2C.Dobberman.Phone.DobbermanService.Authority AuthorityField;
        
        private int AuthorityIdField;
        
        private System.DateTime DateField;
        
        private string DescriptionField;
        
        private string LocationField;
        
        private string MoodField;
        
        private byte[] PhotoField;
        
        private int ReportIdField;
        
        private TAUP2C.Dobberman.Phone.DobbermanService.User UserField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TAUP2C.Dobberman.Phone.DobbermanService.Authority Authority {
            get {
                return this.AuthorityField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorityField, value) != true)) {
                    this.AuthorityField = value;
                    this.RaisePropertyChanged("Authority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuthorityId {
            get {
                return this.AuthorityIdField;
            }
            set {
                if ((this.AuthorityIdField.Equals(value) != true)) {
                    this.AuthorityIdField = value;
                    this.RaisePropertyChanged("AuthorityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mood {
            get {
                return this.MoodField;
            }
            set {
                if ((object.ReferenceEquals(this.MoodField, value) != true)) {
                    this.MoodField = value;
                    this.RaisePropertyChanged("Mood");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReportId {
            get {
                return this.ReportIdField;
            }
            set {
                if ((this.ReportIdField.Equals(value) != true)) {
                    this.ReportIdField = value;
                    this.RaisePropertyChanged("ReportId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TAUP2C.Dobberman.Phone.DobbermanService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authority", Namespace="http://schemas.datacontract.org/2004/07/TAUP2C.Dobberman.Web.Services")]
    public partial class Authority : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int AuthorityIdField;
        
        private string FacebookPageField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuthorityId {
            get {
                return this.AuthorityIdField;
            }
            set {
                if ((this.AuthorityIdField.Equals(value) != true)) {
                    this.AuthorityIdField = value;
                    this.RaisePropertyChanged("AuthorityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookPage {
            get {
                return this.FacebookPageField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookPageField, value) != true)) {
                    this.FacebookPageField = value;
                    this.RaisePropertyChanged("FacebookPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/TAUP2C.Dobberman.Web.Services")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EmailField;
        
        private string NameField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DobbermanService.IDobbermanService")]
    public interface IDobbermanService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/GetReportsByUserId", ReplyAction="http://tempuri.org/IDobbermanService/GetReportsByUserIdResponse")]
        System.IAsyncResult BeginGetReportsByUserId(int userId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> EndGetReportsByUserId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/CreateNewReport", ReplyAction="http://tempuri.org/IDobbermanService/CreateNewReportResponse")]
        System.IAsyncResult BeginCreateNewReport(TAUP2C.Dobberman.Phone.DobbermanService.Report report, System.AsyncCallback callback, object asyncState);
        
        bool EndCreateNewReport(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/CreateNewUser", ReplyAction="http://tempuri.org/IDobbermanService/CreateNewUserResponse")]
        System.IAsyncResult BeginCreateNewUser(TAUP2C.Dobberman.Phone.DobbermanService.User user, System.AsyncCallback callback, object asyncState);
        
        bool EndCreateNewUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDobbermanService/CreateNewAuthority", ReplyAction="http://tempuri.org/IDobbermanService/CreateNewAuthorityResponse")]
        System.IAsyncResult BeginCreateNewAuthority(TAUP2C.Dobberman.Phone.DobbermanService.Authority authority, System.AsyncCallback callback, object asyncState);
        
        bool EndCreateNewAuthority(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDobbermanServiceChannel : TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetReportsByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetReportsByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateNewReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateNewReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateNewUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateNewUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateNewAuthorityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateNewAuthorityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DobbermanServiceClient : System.ServiceModel.ClientBase<TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService>, TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService {
        
        private BeginOperationDelegate onBeginGetReportsByUserIdDelegate;
        
        private EndOperationDelegate onEndGetReportsByUserIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetReportsByUserIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateNewReportDelegate;
        
        private EndOperationDelegate onEndCreateNewReportDelegate;
        
        private System.Threading.SendOrPostCallback onCreateNewReportCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateNewUserDelegate;
        
        private EndOperationDelegate onEndCreateNewUserDelegate;
        
        private System.Threading.SendOrPostCallback onCreateNewUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateNewAuthorityDelegate;
        
        private EndOperationDelegate onEndCreateNewAuthorityDelegate;
        
        private System.Threading.SendOrPostCallback onCreateNewAuthorityCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DobbermanServiceClient() {
        }
        
        public DobbermanServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DobbermanServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DobbermanServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DobbermanServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetReportsByUserIdCompletedEventArgs> GetReportsByUserIdCompleted;
        
        public event System.EventHandler<CreateNewReportCompletedEventArgs> CreateNewReportCompleted;
        
        public event System.EventHandler<CreateNewUserCompletedEventArgs> CreateNewUserCompleted;
        
        public event System.EventHandler<CreateNewAuthorityCompletedEventArgs> CreateNewAuthorityCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginGetReportsByUserId(int userId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetReportsByUserId(userId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndGetReportsByUserId(System.IAsyncResult result) {
            return base.Channel.EndGetReportsByUserId(result);
        }
        
        private System.IAsyncResult OnBeginGetReportsByUserId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginGetReportsByUserId(userId, callback, asyncState);
        }
        
        private object[] OnEndGetReportsByUserId(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndGetReportsByUserId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetReportsByUserIdCompleted(object state) {
            if ((this.GetReportsByUserIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetReportsByUserIdCompleted(this, new GetReportsByUserIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetReportsByUserIdAsync(int userId) {
            this.GetReportsByUserIdAsync(userId, null);
        }
        
        public void GetReportsByUserIdAsync(int userId, object userState) {
            if ((this.onBeginGetReportsByUserIdDelegate == null)) {
                this.onBeginGetReportsByUserIdDelegate = new BeginOperationDelegate(this.OnBeginGetReportsByUserId);
            }
            if ((this.onEndGetReportsByUserIdDelegate == null)) {
                this.onEndGetReportsByUserIdDelegate = new EndOperationDelegate(this.OnEndGetReportsByUserId);
            }
            if ((this.onGetReportsByUserIdCompletedDelegate == null)) {
                this.onGetReportsByUserIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetReportsByUserIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetReportsByUserIdDelegate, new object[] {
                        userId}, this.onEndGetReportsByUserIdDelegate, this.onGetReportsByUserIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginCreateNewReport(TAUP2C.Dobberman.Phone.DobbermanService.Report report, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateNewReport(report, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndCreateNewReport(System.IAsyncResult result) {
            return base.Channel.EndCreateNewReport(result);
        }
        
        private System.IAsyncResult OnBeginCreateNewReport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TAUP2C.Dobberman.Phone.DobbermanService.Report report = ((TAUP2C.Dobberman.Phone.DobbermanService.Report)(inValues[0]));
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginCreateNewReport(report, callback, asyncState);
        }
        
        private object[] OnEndCreateNewReport(System.IAsyncResult result) {
            bool retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndCreateNewReport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateNewReportCompleted(object state) {
            if ((this.CreateNewReportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateNewReportCompleted(this, new CreateNewReportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateNewReportAsync(TAUP2C.Dobberman.Phone.DobbermanService.Report report) {
            this.CreateNewReportAsync(report, null);
        }
        
        public void CreateNewReportAsync(TAUP2C.Dobberman.Phone.DobbermanService.Report report, object userState) {
            if ((this.onBeginCreateNewReportDelegate == null)) {
                this.onBeginCreateNewReportDelegate = new BeginOperationDelegate(this.OnBeginCreateNewReport);
            }
            if ((this.onEndCreateNewReportDelegate == null)) {
                this.onEndCreateNewReportDelegate = new EndOperationDelegate(this.OnEndCreateNewReport);
            }
            if ((this.onCreateNewReportCompletedDelegate == null)) {
                this.onCreateNewReportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateNewReportCompleted);
            }
            base.InvokeAsync(this.onBeginCreateNewReportDelegate, new object[] {
                        report}, this.onEndCreateNewReportDelegate, this.onCreateNewReportCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginCreateNewUser(TAUP2C.Dobberman.Phone.DobbermanService.User user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateNewUser(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndCreateNewUser(System.IAsyncResult result) {
            return base.Channel.EndCreateNewUser(result);
        }
        
        private System.IAsyncResult OnBeginCreateNewUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TAUP2C.Dobberman.Phone.DobbermanService.User user = ((TAUP2C.Dobberman.Phone.DobbermanService.User)(inValues[0]));
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginCreateNewUser(user, callback, asyncState);
        }
        
        private object[] OnEndCreateNewUser(System.IAsyncResult result) {
            bool retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndCreateNewUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateNewUserCompleted(object state) {
            if ((this.CreateNewUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateNewUserCompleted(this, new CreateNewUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateNewUserAsync(TAUP2C.Dobberman.Phone.DobbermanService.User user) {
            this.CreateNewUserAsync(user, null);
        }
        
        public void CreateNewUserAsync(TAUP2C.Dobberman.Phone.DobbermanService.User user, object userState) {
            if ((this.onBeginCreateNewUserDelegate == null)) {
                this.onBeginCreateNewUserDelegate = new BeginOperationDelegate(this.OnBeginCreateNewUser);
            }
            if ((this.onEndCreateNewUserDelegate == null)) {
                this.onEndCreateNewUserDelegate = new EndOperationDelegate(this.OnEndCreateNewUser);
            }
            if ((this.onCreateNewUserCompletedDelegate == null)) {
                this.onCreateNewUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateNewUserCompleted);
            }
            base.InvokeAsync(this.onBeginCreateNewUserDelegate, new object[] {
                        user}, this.onEndCreateNewUserDelegate, this.onCreateNewUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.BeginCreateNewAuthority(TAUP2C.Dobberman.Phone.DobbermanService.Authority authority, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateNewAuthority(authority, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService.EndCreateNewAuthority(System.IAsyncResult result) {
            return base.Channel.EndCreateNewAuthority(result);
        }
        
        private System.IAsyncResult OnBeginCreateNewAuthority(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TAUP2C.Dobberman.Phone.DobbermanService.Authority authority = ((TAUP2C.Dobberman.Phone.DobbermanService.Authority)(inValues[0]));
            return ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).BeginCreateNewAuthority(authority, callback, asyncState);
        }
        
        private object[] OnEndCreateNewAuthority(System.IAsyncResult result) {
            bool retVal = ((TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService)(this)).EndCreateNewAuthority(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateNewAuthorityCompleted(object state) {
            if ((this.CreateNewAuthorityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateNewAuthorityCompleted(this, new CreateNewAuthorityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateNewAuthorityAsync(TAUP2C.Dobberman.Phone.DobbermanService.Authority authority) {
            this.CreateNewAuthorityAsync(authority, null);
        }
        
        public void CreateNewAuthorityAsync(TAUP2C.Dobberman.Phone.DobbermanService.Authority authority, object userState) {
            if ((this.onBeginCreateNewAuthorityDelegate == null)) {
                this.onBeginCreateNewAuthorityDelegate = new BeginOperationDelegate(this.OnBeginCreateNewAuthority);
            }
            if ((this.onEndCreateNewAuthorityDelegate == null)) {
                this.onEndCreateNewAuthorityDelegate = new EndOperationDelegate(this.OnEndCreateNewAuthority);
            }
            if ((this.onCreateNewAuthorityCompletedDelegate == null)) {
                this.onCreateNewAuthorityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateNewAuthorityCompleted);
            }
            base.InvokeAsync(this.onBeginCreateNewAuthorityDelegate, new object[] {
                        authority}, this.onEndCreateNewAuthorityDelegate, this.onCreateNewAuthorityCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService CreateChannel() {
            return new DobbermanServiceClientChannel(this);
        }
        
        private class DobbermanServiceClientChannel : ChannelBase<TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService>, TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService {
            
            public DobbermanServiceClientChannel(System.ServiceModel.ClientBase<TAUP2C.Dobberman.Phone.DobbermanService.IDobbermanService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetReportsByUserId(int userId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userId;
                System.IAsyncResult _result = base.BeginInvoke("GetReportsByUserId", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> EndGetReportsByUserId(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report> _result = ((System.Collections.ObjectModel.ObservableCollection<TAUP2C.Dobberman.Phone.DobbermanService.Report>)(base.EndInvoke("GetReportsByUserId", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateNewReport(TAUP2C.Dobberman.Phone.DobbermanService.Report report, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = report;
                System.IAsyncResult _result = base.BeginInvoke("CreateNewReport", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndCreateNewReport(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("CreateNewReport", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateNewUser(TAUP2C.Dobberman.Phone.DobbermanService.User user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("CreateNewUser", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndCreateNewUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("CreateNewUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateNewAuthority(TAUP2C.Dobberman.Phone.DobbermanService.Authority authority, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = authority;
                System.IAsyncResult _result = base.BeginInvoke("CreateNewAuthority", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndCreateNewAuthority(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("CreateNewAuthority", _args, result)));
                return _result;
            }
        }
    }
}
