//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DobbermanModel", "FK_AuthorityEntityReportEntity", "Authorities", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TAUP2C.Dobberman.Web.Models.AuthorityEntity), "Reports", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TAUP2C.Dobberman.Web.Models.ReportEntity), true)]
[assembly: EdmRelationshipAttribute("DobbermanModel", "FK_ReportEntityUserEntity", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TAUP2C.Dobberman.Web.Models.UserEntity), "Reports", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TAUP2C.Dobberman.Web.Models.ReportEntity), true)]

#endregion

namespace TAUP2C.Dobberman.Web.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DobbermanEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DobbermanEntities object using the connection string found in the 'DobbermanEntities' section of the application configuration file.
        /// </summary>
        public DobbermanEntities() : base("name=DobbermanEntities", "DobbermanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DobbermanEntities object.
        /// </summary>
        public DobbermanEntities(string connectionString) : base(connectionString, "DobbermanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DobbermanEntities object.
        /// </summary>
        public DobbermanEntities(EntityConnection connection) : base(connection, "DobbermanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AuthorityEntity> Authorities
        {
            get
            {
                if ((_Authorities == null))
                {
                    _Authorities = base.CreateObjectSet<AuthorityEntity>("Authorities");
                }
                return _Authorities;
            }
        }
        private ObjectSet<AuthorityEntity> _Authorities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReportEntity> Reports
        {
            get
            {
                if ((_Reports == null))
                {
                    _Reports = base.CreateObjectSet<ReportEntity>("Reports");
                }
                return _Reports;
            }
        }
        private ObjectSet<ReportEntity> _Reports;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserEntity> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<UserEntity>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<UserEntity> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Authorities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuthorities(AuthorityEntity authorityEntity)
        {
            base.AddObject("Authorities", authorityEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReports(ReportEntity reportEntity)
        {
            base.AddObject("Reports", reportEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(UserEntity userEntity)
        {
            base.AddObject("Users", userEntity);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DobbermanModel", Name="AuthorityEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuthorityEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AuthorityEntity object.
        /// </summary>
        /// <param name="authorityId">Initial value of the AuthorityId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="facebookPage">Initial value of the FacebookPage property.</param>
        public static AuthorityEntity CreateAuthorityEntity(global::System.Int32 authorityId, global::System.String name, global::System.String facebookPage)
        {
            AuthorityEntity authorityEntity = new AuthorityEntity();
            authorityEntity.AuthorityId = authorityId;
            authorityEntity.Name = name;
            authorityEntity.FacebookPage = facebookPage;
            return authorityEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuthorityId
        {
            get
            {
                return _AuthorityId;
            }
            set
            {
                if (_AuthorityId != value)
                {
                    OnAuthorityIdChanging(value);
                    ReportPropertyChanging("AuthorityId");
                    _AuthorityId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AuthorityId");
                    OnAuthorityIdChanged();
                }
            }
        }
        private global::System.Int32 _AuthorityId;
        partial void OnAuthorityIdChanging(global::System.Int32 value);
        partial void OnAuthorityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FacebookPage
        {
            get
            {
                return _FacebookPage;
            }
            set
            {
                OnFacebookPageChanging(value);
                ReportPropertyChanging("FacebookPage");
                _FacebookPage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FacebookPage");
                OnFacebookPageChanged();
            }
        }
        private global::System.String _FacebookPage;
        partial void OnFacebookPageChanging(global::System.String value);
        partial void OnFacebookPageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DobbermanModel", "FK_AuthorityEntityReportEntity", "Reports")]
        public EntityCollection<ReportEntity> Reports
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReportEntity>("DobbermanModel.FK_AuthorityEntityReportEntity", "Reports");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReportEntity>("DobbermanModel.FK_AuthorityEntityReportEntity", "Reports", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DobbermanModel", Name="ReportEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReportEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReportEntity object.
        /// </summary>
        /// <param name="reportId">Initial value of the ReportId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="authorityId">Initial value of the AuthorityId property.</param>
        public static ReportEntity CreateReportEntity(global::System.Int32 reportId, global::System.DateTime date, global::System.String description, global::System.Int32 userId, global::System.Int32 authorityId)
        {
            ReportEntity reportEntity = new ReportEntity();
            reportEntity.ReportId = reportId;
            reportEntity.Date = date;
            reportEntity.Description = description;
            reportEntity.UserId = userId;
            reportEntity.AuthorityId = authorityId;
            return reportEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReportId
        {
            get
            {
                return _ReportId;
            }
            set
            {
                if (_ReportId != value)
                {
                    OnReportIdChanging(value);
                    ReportPropertyChanging("ReportId");
                    _ReportId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ReportId");
                    OnReportIdChanged();
                }
            }
        }
        private global::System.Int32 _ReportId;
        partial void OnReportIdChanging(global::System.Int32 value);
        partial void OnReportIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuthorityId
        {
            get
            {
                return _AuthorityId;
            }
            set
            {
                OnAuthorityIdChanging(value);
                ReportPropertyChanging("AuthorityId");
                _AuthorityId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthorityId");
                OnAuthorityIdChanged();
            }
        }
        private global::System.Int32 _AuthorityId;
        partial void OnAuthorityIdChanging(global::System.Int32 value);
        partial void OnAuthorityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Photo
        {
            get
            {
                return StructuralObject.GetValidValue(_Photo);
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.Byte[] _Photo;
        partial void OnPhotoChanging(global::System.Byte[] value);
        partial void OnPhotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mood
        {
            get
            {
                return _Mood;
            }
            set
            {
                OnMoodChanging(value);
                ReportPropertyChanging("Mood");
                _Mood = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mood");
                OnMoodChanged();
            }
        }
        private global::System.String _Mood;
        partial void OnMoodChanging(global::System.String value);
        partial void OnMoodChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DobbermanModel", "FK_AuthorityEntityReportEntity", "Authorities")]
        public AuthorityEntity Authority
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuthorityEntity>("DobbermanModel.FK_AuthorityEntityReportEntity", "Authorities").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuthorityEntity>("DobbermanModel.FK_AuthorityEntityReportEntity", "Authorities").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AuthorityEntity> AuthorityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuthorityEntity>("DobbermanModel.FK_AuthorityEntityReportEntity", "Authorities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AuthorityEntity>("DobbermanModel.FK_AuthorityEntityReportEntity", "Authorities", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DobbermanModel", "FK_ReportEntityUserEntity", "Users")]
        public UserEntity User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserEntity>("DobbermanModel.FK_ReportEntityUserEntity", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserEntity>("DobbermanModel.FK_ReportEntityUserEntity", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserEntity> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserEntity>("DobbermanModel.FK_ReportEntityUserEntity", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserEntity>("DobbermanModel.FK_ReportEntityUserEntity", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DobbermanModel", Name="UserEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserEntity object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static UserEntity CreateUserEntity(global::System.Int32 userId, global::System.String email, global::System.String name)
        {
            UserEntity userEntity = new UserEntity();
            userEntity.UserId = userId;
            userEntity.Email = email;
            userEntity.Name = name;
            return userEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DobbermanModel", "FK_ReportEntityUserEntity", "Reports")]
        public EntityCollection<ReportEntity> Reports
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReportEntity>("DobbermanModel.FK_ReportEntityUserEntity", "Reports");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReportEntity>("DobbermanModel.FK_ReportEntityUserEntity", "Reports", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
